version: "3.8"

services:

  configserver:
    image: codewithwinnie/configserver:latest
    ports:
      - "8071:8071"
    networks:
      - codewithwinnie



  accounts:
    image: codewithwinnie/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - codewithwinnie
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071

  loans:
    image: codewithwinnie/loans:latest
    ports:
      - "8081:8081"
    networks:
      - codewithwinnie
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071

  cards:
    image: codewithwinnie/cards:latest
    ports:
      - "8082:8082"
    networks:
      - codewithwinnie
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071


networks:
  codewithwinnie: