apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deploment
  labels: 
    app: eurekagserver
spec:
  replicas: 1
  selector:
  matchLabels:
    app: eurekagserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - name: eurekaserver
        image: codewithwinnie/eurekaserver:latest
        ports:
        - containerPort: 8070
        env: 
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom:
            configMapKeyRef:
              name: codewithwinnie-configmap
              key: SPRING_ZIPKIN_BASEURL
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: codewithwinnie-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: codewithwinnie-configmap
              key: SPRING_CONFIG_IMPORT

---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver-service
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8070