version: "3.8"

services:

  configserver:
    image: codewithwinnie/configserver:latest
    ports:
      - "8071:8071"
    networks:
      - codewithwinnie

  eurekaserver:
    image: codewithwinnie/accounts:latest
    ports:
      - "8070:8070"
    networks:
      - codewithwinnie
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071


  accounts_0:
    image: codewithwinnie/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - codewithwinnie
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka


  accounts_1:
    image: codewithwinnie/accounts:latest
    ports:
      - "8090:8080"
    networks:
      - codewithwinnie
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka

  loans:
    image: codewithwinnie/loans:latest
    ports:
      - "8081:8081"
    networks:
      - codewithwinnie
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka

  cards:
    image: codewithwinnie/cards:latest
    ports:
      - "8082:8082"
    networks:
      - codewithwinnie
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka


networks:
  codewithwinnie: